Item:
Name=Failed SSH logins count
Type=Zabbix agent (active)
Key=log.count[/var/log/auth.log,"Failed password",,,skip]
TypeOfInformation=Numeric (unsigned)
Units=logins
UpdateInterval=30s

Trigger:
Name=High number of failed SSH logins on linux-target
Expression=last(/linux-target/log.count[/var/log/auth.log,"Failed password",,,skip])>3
Severity=Warning
OKEventGeneration=Expression
ProblemEventGenerationMode=Single
OKEventCloses=All problems